import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import NextAuthProvider from "@/provider/NextAuthProvider";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  weight: ["100", "200", "400", "600", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
       <html lang="en">
        <body className={`${poppins.className} antialiased`}>
          <header className="py-2 mx-auto md:w-11/12">
            <Navbar></Navbar>
          </header>
          <main className="py-2 mx-auto md:w-11/12 min-h-[calc(100svh-260px)]">
            {children}
          </main>
          <footer className="">
            <Footer></Footer>
          </footer>
        </body>
      </html>
    </NextAuthProvider>
   
  );
}
