import Product from '@/components/layout/home/Product';
import React from 'react';


export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <Product></Product>
        </div>
    );
};

export default page;